### ISSUE TITLE
orphaned admin records

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#739] opened 2017-04-13 15:56 UTC
heya, there are 5319 admin records which have no hierarchy at all:
https://gist.github.com/missinglink/34ec94fd3dcc53c4300ecc8405ab9b5e

originally the one which caught my eye was:
https://whosonfirst.mapzen.com/spelunker/id/85831255

this one should certainly at least belong to United States and North America?

maybe it's possible to run these back through the PIP service to figure out their lineage?

related: https://github.com/whosonfirst-data/whosonfirst-data/issues/173

**Comment by nvkelso** [comment] 2017-04-13 16:43
I suspect these are relics of an earlier PIP workflow for `neighbourhood` which looked for the immediate `locality` parent and harvested the hierarchy from that. But for rural 'hoods which don't have a locality parent this created problems.

**Comment by nvkelso** [comment] 2017-04-13 16:44
@stepps00 can you work with @thisisaaronland to add the hierarchies to these places, please?

**Comment by stepps00** [comment] 2017-11-20 21:27
This is a duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/922. 

I'm going to close this issue (and related PR) and use #922 to track hierarchy updates for the ~360 leftover records that do not have hierarchies.

**Closed by stepps00** 2017-11-20 21:27 UTC
