### ISSUE TITLE
Upgrade neighbourhood records in Hyderabad, India

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#661] opened 2017-02-21 17:50 UTC
This request came in through email support. Snips below:

Our state, Telangana (https://www.openstreetmap.org/relation/3250963),
and our workplace neighbourhood, Prashasan Nagar (https://www.openstreetmap.org/relation/6703400), are missing from the Who's on First gazetteer!

Can you forward this data to your team responsible for WOF? Or can you point us in the right direction where I can contribute?

_______________________________________
_(Edited by stepps00 on 02/21/2017)_

To-do for Hyderabad, India neighbourhood upgrades:

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Upgrade** locality record's shape
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment] 2017-02-21 18:47
We have existing issue(s) open for new India data imports - [here](https://github.com/whosonfirst-data/whosonfirst-data/issues/636) and [here](https://github.com/whosonfirst-data/whosonfirst-data/issues/497). The new Telengana record will be imported into Who's On First once [this commit](https://github.com/whosonfirst-data/whosonfirst-data/pull/660/commits/be538aafe8e77e8be66e03172a3e812faa709a33) lands in `master`. 

We should update the neighbourhood records in Hyperbad, though, so I'll keep this issue open to track progress of the neighbourhood update work.

**Comment by gopi-ar** [comment] 2017-02-22 12:35
@stepps00 the major change of Telangana as a new state in India and also this neighbourhood (Prashasan Nagar) have been in OSM for quite a few years now, how come it's not updated to Pelias? We added "Unwired Labs" to OSM a couple of months ago and that shows up in Pelias just fine..

**Comment by gopi-ar** [comment] 2017-02-22 12:35
@rmglennon correction, it's "Hyderabad" though "Hyper-bad" sounds cooler. :-)

**Comment by stepps00** [comment] 2017-02-22 17:37
hey @gopi-ar - the Pelias service pulls data from more than one source; the administrative data, like the new state of Telengana, is pulled from Who's On First rather than OSM. The new Indian state data should be in Who's On First once we merge an outstanding pull request. Unwired Labs and other venue data seen in Pelias is being brought in from OSM. 

Thanks for filing the issue and letting us know! If you see anything else missing from Who's On First that you'd like to add, fee free to open an issue or file a pull request.. :-)

**Comment by rmglennon** [comment] 2017-02-23 05:43
@gopi-ar - wow, Hyperbad. That is a wonderful failure of typing autocorrect! :)

I have edited the title.

**Comment by SrihariThalla** [comment] 2017-02-27 08:37
@stepps00 Just wanted to know if you have any ETA for the update of the commit https://github.com/whosonfirst-data/whosonfirst-data/pull/660/commits/be538aafe8e77e8be66e03172a3e812faa709a33 into master!

**Comment by stepps00** [comment] 2017-02-27 17:29
Hi @SrihariThalla - that PR is close to being ingested into `master`. It will be merged late next week at the earliest, so in the next fortnight - early March. I will keep this issue open until it is merged.

**Comment by SrihariThalla** [comment] 2017-02-28 09:45
Thanks, Stephen! I wish I knew how to contribute.

**Comment by stepps00** [comment] 2017-02-28 16:26
@SrihariThalla - here's a brief outline of how to contribute to Who's On First: [our contributing documentation](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/CONTRIBUTING.md). There may be additional steps to take, but if you'd ever like to contribute via a GitHub pull request that adds/updates WOF records, we're happy to work with you!

**Comment by SrihariThalla** [comment] 2017-03-02 07:07
Thanks, Stephen. I'll start checking out the data around in my city to start with. Love to work you!

**Comment by SrihariThalla** [comment] 2017-03-17 07:38
@stepps00 Does the pull #660 include the [newly formed districts](https://en.wikipedia.org/wiki/List_of_districts_in_Telangana) of Telangana (from 10 to 31)? I've checked [Statoids](http://www.statoids.com/yin.html) and I don't see them. It seems Statoids data is `as of 2015`?

**Comment by stepps00** [comment] 2017-03-17 14:51
Hi @SrihariThalla - yes, it does. [Here](https://github.com/whosonfirst-data/whosonfirst-data/blob/be538aafe8e77e8be66e03172a3e812faa709a33/data/110/880/597/9/1108805979.geojson) is a link showing the geometry of the new Telengana region and [here](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/be538aafe8e77e8be66e03172a3e812faa709a33/data/110/880/597/9/1108805979.geojson) is a link to the raw data for the record.

Statoids data for India does not include this region, but we've made sure that our records reflect the current state of regional administrative divisions in India :)

**Comment by SrihariThalla** [comment] 2017-03-22 12:24
Hi @stepps00! 

It seems [DataMeet](http://projects.datameet.org/maps/districts/) doesn't have the new districts of Telangana yet.

As a side note, the data may not be "legally obtained" as DataMeet "scraped" a government website which has a disclaimer prohibiting to copy and distribute the data from that website. Although, at least in India, that's not a big deal and copyright laws are not so rigid as they are in the US or the others.
I have [asked for the same on their GitHub repo](https://github.com/datameet/maps/issues/13).

If the data is legal, I'm much more interested in [replicating it on OSM](https://forum.openstreetmap.org/viewtopic.php?id=56773). (Even [Bhuvan](http://bhuvan.nrsc.gov.in/state/TS) has the old list. Although I am not sure about their sharing policy.)

(P.S. I am not quite sure where DataMeet data is linked in #363.)

**Comment by stepps00** [comment] 2017-03-22 17:31
@SrihariThalla - thanks for the info.. I'll take a look at the DataMeet license, if that is the case then we will need to find a new set of data to import that has a CC0, CC-BY, or equivalent license.

And that is my mistake; the issue is #636, not #363. I've updated the above comment.

**Comment by gopi-ar** [comment] 2018-08-05 11:44
@stepps00 any update on this? The new state `Telangana` never made it to the master data..

**Comment by stepps00** [comment] 2018-08-06 04:52
Hey @gopi-ar - you can view the Telengana record [here](https://spelunker.whosonfirst.org/id/1108805979/).

I've recently been chatting with the folks at DataMeet about other admin data imports for WOF. WOF currently has [districts of India](https://spelunker.whosonfirst.org/id/85632469/descendants/?exclude=nullisland&placetype=county) as of ~2011, but we're hoping to get a more recent file set for import that represent districts as of 2018.

As for this issue specifically, are you aware of any open data for the neighbourhoods of Hyperabad?

**Comment by gopi-ar** [comment] 2018-09-29 07:57
Thanks @stepps00! Looks like the main record's spelling is incorrect. It's `Telangana` not `Telengana`. Also on my latest installation of the PIP service, it still says Hyderabad is part of Andhra Pradesh, not Telangana. Looks like it still belongs to both admin boundaries in the dataset ([1](https://spelunker.whosonfirst.org/id/1108696315/) & [2](https://spelunker.whosonfirst.org/id/102030059/)).

As for neighbourhood data, we've added a lot of stuff to OSM. For higher level stuff like admin boundaries, wouldn't an import from OSM be easier? They have more contributors and data changes faster. Is it a license issue or something else?

**Comment by nvkelso** [comment] 2018-10-01 17:31
Correct, the ODbL license used by OpenStreetMap (OSM) is not compatible with Who's On First and prevents an import.

What sources are you using to add to OSM, can those originals be imported to Who's On First?

**Comment by stepps00** [comment] 2018-10-01 17:34
Thank you for the tips, @gopi-ar - I've filed #1330, which corrects the name to Telangana and removes the (incorrect) dual-hierarchy of Hyperabad and descendant records. Once merged, that should address the issue mentioned in https://github.com/whosonfirst-data/whosonfirst-data/issues/661#issuecomment-425625456.

We will keep this issue open until neighbourhood records in Hyperabad are updated, though.

**Comment by gopi-ar** [comment] 2018-10-03 05:44
@nvkelso nothing available online, unfortunately. I understand a number of datasets that WOF relies on require attribution (CC etc) already. Why not import OSM data into a separate repo from people complying with ODbL can pull data? It'll be like the old "you-can-install-mp3-plugins-yourself-but-ubuntu-won't-ship-them" work-around.

**Comment by stepps00** [comment] 2019-12-04 23:47
This was completed through https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/16.

**Closed** 2019-12-09 18:38 UTC
Labels: LOE:High, enhancement, neighbourhood, user-reported
