### ISSUE TITLE
New locality geometries for Switzerland

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1334] opened 2018-10-03 18:44 UTC
Heya,

Following on from a chat today with @stepps00.

Many of the locality shapes in WOF for Switzerland are kinda funky (eg https://spelunker.whosonfirst.org/id/101748453/).

So I set out to hunt down some better ones on the SwissTopo portal and managed to find [official shapes for the Swiss towns/villages](https://www.cadastre.ch/content/cadastre-internet/en/services/service/plz.html)!

For the larger communes, the shape is coterminous to the village, but many communes also contain more than one village, so in those cases, the two geometries are obviously not coterminous.

The existing `local_admin` shapes for the communes are available in [swissBOUNDARIES3D_LV95.zip](https://shop.swisstopo.admin.ch/en/products/landscape/boundaries3D) in the `Hoheitsgebiet` layer.

The new `locality` shapes I'd like to add are available in the [PLZO_SHP_LV95.zip](http://data.geo.admin.ch/ch.swisstopo-vd.ortschaftenverzeichnis_plz/PLZO_SHP_LV95.zip) file. The data is split up into two files within that zip which need to be merged.

The geometry is in `PLZO_OS` and the names are in `PLZO_OSNAME`, there are also other `.dbf` files which provide additional metadata which we might want to import.

I exported a reprojected `.geojson` file from QGIS which is [available here for spot checking](https://s3.amazonaws.com/geocodeearth-missinglink/ch_village.geojson.gz).

This was produced by loading `PLZO_OS` and `PLZO_OSNAME` layers, then selecting the 'Properties' dialog for `PLZO_OS`, choosing 'Joins' and then hitting `+` and adding a join with the following settings:

- Join Layer: PLZO_OSNAME
- Join Field: OS_UUID
- Target Fields: UUID

The file contains 4037 localities which I hope we can use to fully replace the existing geometries.
Spelunker lists [7147 localities currently under Switzerland]((https://spelunker.whosonfirst.org/id/85633051/descendants/?exclude=nullisland&placetype=locality).
) so it seems that some would need to be removed?

**Comment by nvkelso** [comment] 2018-10-03 19:06
Nice sleuthing! Could be the count difference is from point locations versus polygons. Depending on how the data falls we could either keep the extra localities as localities or downgrade them to neighbourhoods.

**Comment by missinglink** [comment] 2018-10-03 19:14
I'm not sure if point vs polygon accounts for the difference, the `PLZO_OS` file seems to cover the country without any gaps, so it wouldn't leave much room for the points, do you think there are some really small villages not covered in the `PLZO_OS` file?

Looking at what [we currently have](https://spelunker.whosonfirst.org/id/85633051/descendants/?exclude=nullisland&placetype=locality) listed for localities we can probably also improve the labels, for instance `Stadt Winterthur (Kreis 1)` could simply be `Winterthur`.

**Comment by missinglink** [comment] 2018-10-03 19:19
<img width="1118" alt="screen shot 2018-10-03 at 21 16 18" src="https://user-images.githubusercontent.com/738069/46433726-eb5fc280-c751-11e8-8c26-b7f2f3ac98d9.png">
<img width="833" alt="screen shot 2018-10-03 at 21 18 19" src="https://user-images.githubusercontent.com/738069/46433731-f0247680-c751-11e8-883d-234764bbb321.png">

note: the voillage of 'Belp' near Bern City is a different shape to its Commune

**Comment by missinglink** [comment] 2018-10-04 18:12
I looked for the function `ST_PossiblyMostlyEqual` and it doesn't exist :(

**Comment by heebj** [comment] 2019-06-09 10:02
Hi there, are there any news on this?
I am using Pelias here in Switzerland and a lot of the localities returned from geocoding seem to be wrong. Through a bit of research I learned that this has the cause in often wrong locality boundaries while the localadmin boundaries seem to be correct.

Another example for this is Schaffhausen. In this example the locality boundaries completely different than the localadmin boundaries which leads to wrong results in Pelias:
https://spelunker.whosonfirst.org/id/101876061/

Does a locality have to be a point or polygon? Sometimes it seems to be the one and sometimes the other...

The SwissTopo data seems promising. Please let me know if I can help you somehow :-)

**Comment by stepps00** [comment] 2019-06-10 17:37
Hey @heebj - thanks for following up.. this is still on the list of to-dos, but we'll prioritize this and try to get an update out sometime in the next few weeks.

As far as point versus polygon localities, both are valid geometry types of WOF records. Ideally, we have an accurate polygon that represents the locality boundary, but when these aren't available, we use points (from sources like GeoNames and the Quattroshapes Point Gazetteer). Once we introduce this dataset to WOF in Switzerland, though, the locality records will have polygon geometries.

I'll reach out in this issue once we start working on updates and ping you. Thanks again!

**Comment by heebj** [comment] 2019-06-10 19:31
Thats great! Thanks a lot :-)

**Comment by zifeo** [comment] 2019-06-10 23:35
@stepps00 Is there a way to help? We are also highly affected by those weird geometries (e.g. https://spelunker.whosonfirst.org/id/404328283/) and we would like to help having better data.

**Comment by zifeo** [comment] 2019-06-11 12:58
Here is an example of a wrong Geneva geometry: https://spelunker.whosonfirst.org/id/101748445/
The correct one seems also be in the system: https://spelunker.whosonfirst.org/id/404328283/

**Comment by stepps00** [comment] 2019-06-11 17:37
Thanks for the links @zifeo 

I need to spend more time looking at the WOF records in Switzerland, but from what I remember, the localadmin geometries are Quattroshapes-sourced, which come from SwissTopo. The locality records are a "mixed bag" of polygon and point geometries from multiple sources. Other placetypes (country, region, county) are likely okay, though we can update with more precise geometries.

You'll notice the localadmin of Geneva is accurate, but the locality is not. What likely needs to happen is we'll need to reconcile the locality placetype records and the localadmin placetype records, using concordance values and/or geometry matching in QGIS.

We could use help on:
- Creating a source for this new data, via the [sources repo](https://github.com/whosonfirst/whosonfirst-sources#adding-a-new-source)
- Ensuring that the [region records](https://spelunker.whosonfirst.org/id/85633051/descendants/?exclude=nullisland&placetype=region) in Switzerland have correct name translations

It would also be helpful to have a GeoJSON or shapefile with new locality geometries and the corresponding `wof:id` value for that locality in an attribute field.

Thanks again and we'll make sure to update this issue once records/branches are updated. Feel free to reach out if you have any questions.

**Comment by zifeo** [comment] 2019-06-11 21:53
@stepps00 Thanks for getting back. I am quite new to the Whosonfirst world but eager to contribute.

I have been exploring the wof records already and I am missing the history/contextual information. For example, what should each place type correspond to? If localadmin maps to the municipalities, what should locality be? There is no coarser level in Switzerland. Why points at that level?

I can definitely create a new source. However I would need first to understand the underlying structure that should appear in it (with respect to the current one below)?

Is there any reading about those points?

https://github.com/whosonfirst-data/whosonfirst-data-postalcode-ch seems correct
https://github.com/whosonfirst-data/whosonfirst-data-venue-ch not verified
https://github.com/whosonfirst-data/whosonfirst-data-admin-ch troublesome (see below)

Related readings : https://github.com/whosonfirst-data/whosonfirst-data/issues/897, https://github.com/whosonfirst-data/whosonfirst-data/issues/898

Country-level : polygones, correct, correspond to country
<img width="510" alt="image" src="https://user-images.githubusercontent.com/9053709/59307619-25994080-8c9f-11e9-9c77-0eec82b889b8.png">
[Opendata 2019](https://opendata.swiss/en/dataset/swissboundaries3d-landesgrenzen)

Country : polygones, correct, correspond to [cantons](https://en.wikipedia.org/wiki/Cantons_of_Switzerland)
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9053709/59307602-203bf600-8c9f-11e9-9bf3-e918deccd248.png">
[Opendata 2019](https://opendata.swiss/en/dataset/swissboundaries3d-kantonsgrenzen)

County : polygones, correct, correspond to [districts](https://en.wikipedia.org/wiki/Districts_of_Switzerland)
<img width="513" alt="image" src="https://user-images.githubusercontent.com/9053709/59307593-19ad7e80-8c9f-11e9-9835-6dd645b13b09.png">
[Opendata 2019](https://opendata.swiss/en/dataset/swissboundaries3d-bezirksgrenzen)

Localadmin : polygones and points (!?), missing (namely Zürich), correspond to [municipalities](https://en.wikipedia.org/wiki/Municipalities_of_Switzerland)
<img width="513" alt="image" src="https://user-images.githubusercontent.com/9053709/59307568-10bcad00-8c9f-11e9-8afc-acd9477c8e3e.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/9053709/59308325-16b38d80-8ca1-11e9-87d4-fa0842c71cd7.png">
[Opendata 2019](https://opendata.swiss/en/dataset/swissboundaries3d-gemeindegrenzen)

Locality : polygones and points (even in South of America...), incorrect, what is the correspondance?
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9053709/59307550-0a2e3580-8c9f-11e9-9375-04659a143e62.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/9053709/59308290-f84d9200-8ca0-11e9-9939-1a10ce0bd642.png">

**Comment by nvkelso** [comment] 2019-06-12 00:38
@zifeo Thanks for your interest! There are several equivalent PRs that cover the same work:

- **France** `localadmin` & `locality`: https://github.com/whosonfirst-data/whosonfirst-data/pull/1343
- **Germany** `localadmin` & `locality`: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1

The France PR has a full run down of the steps needed, I recommend following that for Switzerland. This is on our medium-term priority list so if you want it in the next 2-6 weeks we'd be happy to help you move it faster if you take on most the work.

> I have been exploring the wof records already and I am missing the history/contextual information. For example, what should each place type correspond to? If localadmin maps to the municipalities, what should locality be? There is no coarser level in Switzerland. Why points at that level?

Who's On First has a complicated relationship with `localadmin` and `locality`. We view the `locality` as being the most basic building block for all the administrative structure in the gazetteer. It's also most in line with how the USA orders most of it's administration. But In the New England section of the USA, and in most of Europe, `localadmin` forms the basic building block. 

Think of `localadmin` as completely covering a country, while `locality` being isolated urban and rural settlements with wide gaps between them, and sometimes countries have **both**. As you can see with the France PR, we have to reconcile these two concepts so they can exist side-by-side so we can support structures all countries, and because geocoders like Pelias have different biases (perhaps because of where their author's are from) and we want to support a varienty of geocoders. 

Generally the work is around matching up `localadmin` and `locality` that are just one "city" and doing some work in WOF to mark them as "the same", copying some properties and geometries back and forth. And then for the `localadmin` that are more rural and contain multiple settlements / villages / etc taking a different approach.

**Comment by heebj** [comment] 2019-06-12 08:16
@zifeo in my understanding `localadmin` corresponds to the smallest political structure in Switzerland i.e. the municipality/commune. However there are a lot of municipalities which contain multiple villages. An example is Glarus which merged all its municipalities for efficieny reasons into just 3 municipalities: "Glarus Nord", "Glarus", "Glarus Süd". Each contains multiple vilages like "Näfels", "Netstal", "Niederurnen", etc.
https://en.wikipedia.org/wiki/Canton_of_Glarus#Municipalities

**Comment by zifeo** [comment] 2019-06-12 21:58
@heebj Yes, we could use some byproduct of https://opendata.swiss/en/dataset/swissnames3d-geografische-namen-der-landesvermessung.

@stepps00 @nvkelso Would that licensing work?

**Comment by nvkelso** [comment] 2019-06-12 22:00
The mixed commercial use is problematic, the CC-BY part is very workable though.

**Comment by zifeo** [comment] 2019-06-13 14:22
@nvkelso I believe the full license file is available [here](https://www.swisstopo.admin.ch/en/home/meta/conditions/geodata/free-geodata.html). WDYT?

Side question on `locality` level, should we avoid overlapping polygones within the layer?

**Comment by nvkelso** [comment] 2019-06-13 16:48
The two license statements say different things about commercial use so we'd need to clarify that, but it looks promising.

> Side question on `locality` level, should we avoid overlapping polygones within the layer?

Generally we try to _avoid_ having overlapping polygons in a single **placetype** layer. If there are alternate points of view, like for neighbourhoods or for disputed country boundaries, we store those in _alt-geometry_ files.

But sometimes a place at one **placetype** level is "unitary" like a city-state so we generally duplicate the feature between placetypes and mark it `coterminous` with the others (our practice has been to do this for common placetypes, but add placetype alts for common-optional).

**Comment by zifeo** [comment] 2019-06-16 21:26
Thanks for the details. I would suggest to replace/match all the current data with the latest Swisstopo data (01.01.2019, already existing as a source) as such:

Country:
![image](https://user-images.githubusercontent.com/9053709/59569682-6e7d3a80-908d-11e9-8de9-8ba69337dfca.png)

Region:
![image](https://user-images.githubusercontent.com/9053709/59569688-79d06600-908d-11e9-8e1f-c5492722d49c.png)

County (no "derived-from-regions" county when there is no county inside a region):
![image](https://user-images.githubusercontent.com/9053709/59569691-81900a80-908d-11e9-89c3-28aa13e1c5fd.png)

Localadmin:
![image](https://user-images.githubusercontent.com/9053709/59569693-88b71880-908d-11e9-943c-615275abb65c.png)

Locality:
![image](https://user-images.githubusercontent.com/9053709/59569697-9076bd00-908d-11e9-99e5-5db176b8641d.png)

Neighborhood (data exists, however not sure of the implication of adding this layer for the geocoders):
![image](https://user-images.githubusercontent.com/9053709/59569700-98366180-908d-11e9-9223-c371c54fc962.png)

@nvkelso @stepps00 I can provide you with the processing scripts so you can directly derive these geojson. Not sure I have enough knowledge to correctly ingest them into the current dataset. Happy to try if you have some step-by-step demo though.

@heebj What do you think?

**Comment by nvkelso** [comment] 2019-06-18 09:00
> County (no "derived-from-regions" county when there is no county inside a region):

We sometimes create `statistical_gore` fillers for those "empty" areas and mark them as not illegible for hierarchy labels. 

> Neighborhood (data exists, however not sure of the implication of adding this layer for the geocoders):

Wow, that's amazing coverage! Do they have useful names or are they for election purposes? Can you zoom into a specific city and include labels on the screenshot?

Yes, once we have data prepp'd that'll make easier lift for @stepps00 to ingest or we should also use this as opportunity to better document the process :)

**Comment by zifeo** [comment] 2019-06-18 10:41
Ok, the names of neighborhood match quite well the common names people usually use to talk about 3-4 streets together. Official denominations for election stops at the localityadmin level.

![image](https://user-images.githubusercontent.com/9053709/59675493-a4bdd580-91c5-11e9-8806-de7fae66b38c.png)

Extract from the screen:
-  St-Gervais - Temple
-  St-Gervais - Les Bergues
-  Chez Chevassu
-  Maison-Royale
-  Camille-Martin
-  La Dôle
-  Concorde
-  Les Délices
-  Grand Essert
-  La Grange
-  Prés-de-la-Gradelle
-  Dorcière
-  James-Fazy
-  Les Charmilles

**Comment by nvkelso** [comment] 2019-06-18 10:48
Most excellent! :)

**Comment by heebj** [comment] 2019-06-18 15:49
Hey @zifeo, this are fantastic news! Thanks a lot for your work!!

Can you post pictures of the localities Feuerthalen (ZH) und Steinach (SG) to verify that the problems are gone?

**Comment by zifeo** [comment] 2019-06-18 23:12
@heebj for instance we have a correct Shaffhausen localadmin and locality. The slight edges mismatches come from the fact that I simplify the polygons before plotting, otherwise it is fine.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/9053709/59725271-5f34f300-922d-11e9-8243-3ff79a71a2c1.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/9053709/59725295-770c7700-922d-11e9-8f68-fd4cccaaacc2.png">

Feuerthalen
<img width="499" alt="image" src="https://user-images.githubusercontent.com/9053709/59725729-13834900-922f-11e9-8c1d-9f16ef1412b4.png">

Steinach
<img width="499" alt="image" src="https://user-images.githubusercontent.com/9053709/59725738-21d16500-922f-11e9-86e7-52170042d0a8.png">

**Comment by heebj** [comment] 2019-06-19 21:28
That looks good! Thanks for the pictures!

I am wondering why the locality is always smaller than the localadmin even if there is only one locality within a localadmin... But I must admit that I am not very experienced in geo data so I guess this is correct.

**Comment by zifeo** [comment] 2019-07-14 22:50
@nvkelso @stepps00 any news on this point? how can I give you pre-processing scripts and helping you further?

**Comment by SToto98** [comment] 2019-07-15 13:15
Hi @nvkelso @stepps00 
I'm with @zifeo on this topic. It's a huge problem for us right now. Please, give us your feedback on this topic so we can help. We are really commited to fix this as soon as possible. We just need your direction 👍

**Comment by stepps00** [comment] 2019-07-15 18:19
@zifeo - happy to take a look at the preprocessing scripts and any GeoJSON/shapefiles you have already processed. I think there was some discrepancy in the source licensing, I can take a look at that as well this week.

If you are able to upload the scripts and any processed data to a Gist or Git repo and post links in this issue, I can poke around and ping you with any questions.

Thanks @SToto98 @heebj for also taking a look!

**Comment by zifeo** [comment] 2019-07-15 22:37
@stepps00 here you go https://github.com/zifeo/whosonfirst-data-ch :)

**Comment by stepps00** [comment] 2019-07-16 02:07
@zifeo I seem to be hitting errors when running the ipynb file (using runipy) though I do have the `pandas_bokeh` module installed:

```
 07/15/2019 07:03:47 PM INFO: Cell raised uncaught exception: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-155682a4d358> in <module>()
      4 from io import BytesIO
      5 from geopandas.tools import sjoin
----> 6 import pandas_bokeh
      7 import geopandas as gpd
      8 from bokeh.util.warnings import BokehDeprecationWarning

/usr/local/lib/python2.7/site-packages/pandas_bokeh/__init__.py in <module>()
     43     plot_bokeh = CachedAccessor("plot_bokeh", FramePlotMethods)
     44     pyspark.sql.dataframe.DataFrame.plot_bokeh = plot_bokeh
---> 45 except ModuleNotFoundError:
     46     pass

NameError: name 'ModuleNotFoundError' is not defined
07/15/2019 07:03:47 PM INFO: Shutdown kernel
07/15/2019 07:03:48 PM WARNING: Exiting with nonzero exit status
```

Thoughts?

**Comment by zifeo** [comment] 2019-07-16 08:34
@stepps00 I am not sure pandas_bokeh is compatible with python 3. Can you retry with python 3 or remove the library (it is only used to have interactive plots).

**Comment by stepps00** [comment] 2019-07-16 19:54
Thanks @zifeo - I ditched the `pandas_bokeh` module and was able to write the GeoJSON files (did not include properties). I'm going to poke around the data and file a PR in the https://github.com/whosonfirst-data/whosonfirst-data-adminn-ch repository, likely sometime next week.

**Comment by zifeo** [comment] 2019-07-16 20:22
@stepps00 Great, let me know if you have any question.

There is one more thing we could improve - the postal codes. When I look at the picture [here](https://github.com/whosonfirst/whosonfirst-placetypes), would it be possible to add the level postalcode in addition to localadmin and locality? What is the impact of this on geocoders? In fact in the Switzerland's history, lots of municipalities mergers happened and the meaning of postal codes is blurry (e.g. not necessarily corresponding to a specific localadmin nor to a locality).

**Comment by stepps00** [comment] 2019-07-17 00:59
@zifeo WOF actually has postalcode data in Switzerland in a separate repository. You can find it here: https://github.com/whosonfirst-data/whosonfirst-data-postalcode-ch

I have not reviewed or compared the postalcode data in WOF to the source data recently, but it is definitely possible for us to update our postalcode geometries. I am unsure about the specific geocoder impacts, but if you'd like to dive into the postalcode data and let us know if you find any issues, we'd welcome any insights.

**Comment by zifeo** [comment] 2019-07-18 13:30
@stepps00 Does Pelias [WOF lookup](https://github.com/pelias/wof-admin-lookup) use postalcode or admin data? From a quick look, this is not clear to me.

I just pushed an updated containing correction about the projections (the original crs was not always initiated correctly - leading to ~200m shifts) and added the postal codes resolutions so you can get more details. If the postal codes should be linked or attached to localadmin, then I would suggestion to replace the localadmin layer with the postal codes ones.

**Comment by nvkelso** [comment] 2019-07-18 16:59
@orangejulius can provide info on how WOF is used in Pelias.

Postal localities is something separate from `localadmin`. There's overlap for sure, but in WOF they are separate concepts.

**Comment by orangejulius** [comment] 2019-07-18 17:02
We don't do any sort of lookup for postal codes, based on geometry or otherwise.

All postalcodes in Pelias are strings that come from original address records in either OSM or OpenAddresses, and aren't associated with the WOF ID for that postalcode (although it would be very cool if we could at least associate the ID).

**Comment by zifeo** [comment] 2019-07-19 08:59
@orangejulius Thanks. There is still something I do not get. The description in the Pelias WOF lookup tool says: 
> So, for Pelias we actually ignore all admin hierarchy information from individual records, and generate it ourselves from the polygon data in Who's on First.

So the postal code and its geometry must somehow derived be from WOF? The main issue we currently have is that Pelias is returning wrong postal codes and admin data after importing openaddresses or custom addresses (see this case https://spelunker.whosonfirst.org/id/101748445/).

**Comment by orangejulius** [comment] 2019-07-19 10:17
@zifeo that description is accurate if you consider a postal code to be a part of the address, rather than administrative hierarchy. It may not be technically correct everywhere but that's how Pelias thinks of it. So no, postal codes and geometries do NOT come from WOF.

If you want to open an issue in https://github.com/pelias/pelias/ describing some of the specific openaddresses records that are not behaving properly, we can look into it. But I suspect what you'll find is the postalcode that comes with the address in the datasource used by OpenAddresses is incorrect.

**Comment by zifeo** [comment] 2019-07-19 12:15
@orangejulius Here you go: https://github.com/pelias/pelias/issues/811.

Maybe the previous question should be clearer about the meaning of postal codes. In Switzerland a postalcode geometry (https://data.geo.admin.ch/ch.swisstopo-vd.ortschaftenverzeichnis_plz/PLZO_SHP_LV95.zip) may correspond to multiple postal codes number and/or names. One might sees as a pair composed of a number and a name pointing to a geometry. 

For instance:
- 1217 Meyrin refers to localadmin Meyrin and locality Meyrin
- 1216 Cointrin refers to localadmin Meyrin and locality Cointrin
- 1217 Cointrin should arguably be *understood* and *redirected* onto 1216 Cointrin

Second example:
- 3961 Zinal refers to localadmin Anniviers and locality Zinal
- 3961 St-Luc refers  to localadmin Anniviers and locality St-Luc

@stepps00 This is why we might better consider the postal-codes geometries `postal_codes` rather than "exact" locality geometries `localities` in https://github.com/zifeo/whosonfirst-data-ch/blob/master/notebooks/source.ipynb. So the Swiss territory should be fully covered at that level.

**Comment by stepps00** [comment] 2019-07-19 17:46
Thanks for the info @zifeo 

I'm updating Switzerland geometries one placetype at a time; I've updated region records and am currently working through the county placetype. Next week, I plan on starting the localadmin level records, then the locality placetype.

In France, Germany, and a handful of other countries, we've previously done the same work and essentially duplicate the localadmin and locality placetype polygons - by using various property flags, this method has worked well with the WOF placetype structure. It seems like the postalcode geometries also need to be considered in Switzerland, though. When I cross that bridge next week, I'll poke around the locality/localadmin polygons, as well as the postalcode geometries and reach out if I have any questions.

**Comment by missinglink** [comment] 2019-08-05 11:39
testcase: https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/blob/master/data/101/766/263/101766263.geojson

**Closed** 2019-08-12 05:04 UTC

**Comment by zifeo** [comment] 2019-08-12 08:30
@stepps00 Thanks for this amazing work! Is the WOF data already ready as an export or should we wait 24 hours to give it a try?

**Comment by stepps00** [comment] 2019-08-12 14:38
@zifeo - the updates are currently available in each GeoJSON record in the https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/ repository, but the distribution files on https://dist.whosonfirst.org/ will be updated within the next ~24 hours.

**Comment by heebj** [comment] 2019-08-12 16:21
Sounds great! Thanks a lot for your work @stepps00 and @zifeo!

@missinglink do you already know when geocode.earth will be updated with the new data?

**Comment by zifeo** [comment] 2019-08-14 09:49
@stepps00 I just had look and the hierarchy seems to be perfect now! Nonetheless I still see some weird artefacts from the old geometry in the locality level (only points are plotted). For example, is this behaviour normal?
![image](https://user-images.githubusercontent.com/9053709/63011815-5f4a1b80-be89-11e9-857e-8fc4e989beeb.png)

**Comment by stepps00** [comment] 2019-08-14 16:27
Hey @zifeo - good to hear the hierarchies look better. You will see some artifacts like this because Who's On First does not delete or remove records, instead we flag them as [not current](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/mz#is_current) and sometimes [supersede](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/wof#superseded_by) them into new records.

The locality points in your screenshot should be marked with a `mz:is_current` value of `0`. They should also be superseded into a new record with a `neighbourhood` placetype.

Additionally, you'll notice some odd horizontal striping of geometries. We suspect some of these points had less than ideal geometric precision, so we flagged some of those new neighbourhood records with an [`mz:is_funky`](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/mz#is_funky) value of `1`.

Filtering out any of these "funky" neighbourhoods, the (point) coverage should look something like: 

<img width="1261" alt="Screen Shot 2019-08-14 at 7 44 37 AM" src="https://user-images.githubusercontent.com/18567700/63037904-e640c900-be74-11e9-8460-0a70416edb17.png">

Notice that horizontal striping is now gone.. let me know if there are any other questions!

**Comment by zifeo** [comment] 2019-08-16 12:34
@stepps00 Thanks for that information. The hierarchy is now looking good, however Pelias seems to still have the same issue, namely https://github.com/pelias/pelias/issues/811. @orangejulius @missinglink how does Pelias behave when filtering old geometries?

**Comment by orangejulius** [comment] 2019-08-16 14:05
@zifeo Pelias should respect all the WOF flags that indicate current records. Most likely, the issue is that the [tar](https://dist.whosonfirst.org/bundles/) and [sqlite](https://dist.whosonfirst.org/sqlite/) planet files are out of date, and those are the ones Pelias uses by default.

If you want to get around that for now, you can download [whosonfirst-data-admin-ch-latest.db](https://dist.whosonfirst.org/sqlite/whosonfirst-data-admin-ch-latest.db.bz2) and use it in place of `whosonfirst-data-latest.db`. As long as you don't run the WOF downloader (such as through `pelias download wof` or `pelias download all`), it should work.

**Comment by zifeo** [comment] 2019-08-17 20:10
@orangejulius Nice catch! I sadly have still the same results even with the recent data-admin-ch bundle. Either this is caused by another issue or that polygon still influence the pip service. I am using importPlace = 85633051, maybe the correct country id has changed?
