### ISSUE TITLE
pull in alternative names (different languages) from geonames

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#849] opened 2017-07-04 20:45 UTC
heya,

re: this issue https://github.com/pelias/pelias/issues/605, the user has reported that https://whosonfirst.mapzen.com/spelunker/id/101748819 has a concordance to http://www.geonames.org/2910831/hannover.html but the `alternative names` information has not been copied across.

is it possible for us to pull these names in other languages across from geonames in to WOF in some sort of a batch process?

if possible that would save a bunch of time manually entering them via boundary issues

thanks!

**Comment by nvkelso** [comment] 2017-07-04 23:25
Duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/806, planned for this quarter.

**Closed by nvkelso** 2017-07-04 23:25 UTC
