### ISSUE TITLE
Two Delhi entries with the same population

### ISSUE THREAD

**Issue by f4rk4sh** [whosonfirst-data/whosonfirst-data#2142] opened 2023-06-14 13:36 UTC
I checked [Delhi](https://spelunker.whosonfirst.org/id/102030425/) (102030425, Delhi, locality, 16314838) and  [Delhi](https://spelunker.whosonfirst.org/id/890506443/) (890506443, Delhi, locality, 16314838). These entries are different, but have the same `place_name`, `place_type`, and `population`. Looks like a mistake, because the location of the second Delhi is small, and the population seems too large for it.

**Comment by nvkelso** [comment] 2023-06-14 21:13
@f4rk4sh Can you check again? We just updated our Indian locality data (blog post coming soon) and I can't reproduce your problem using today's data. 

It's somewhat common for place names to repeat within the same country, even at the same placetype. It's less common but still possible for a place name at the same placetype to repeat in the same region within that country. 

I have seen problems in the past where a small village has gotten the population of it's larger "cousin" in error so it is useful to report problems like that here. Thanks!

**Comment by f4rk4sh** [comment] 2023-06-15 09:45
@nvkelso I checked [Delhi](https://spelunker.whosonfirst.org/id/890506443/) (890506443), and the population now is 3246. Thank you!

**Comment by nvkelso** [comment] 2023-06-15 14:48
Woot! Closing as complete.

**Closed** 2023-06-15 14:48 UTC
