### ISSUE TITLE
Is London a locality that entirely contains the much smaller City of Westminster region?

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#225] opened 2016-03-14 15:47 UTC
I have a data question to see if i’m understanding something correctly.  In spelunker I see that City of Westminster is a region (https://whosonfirst.mapzen.com/spelunker/id/85684061/).  I also see that London is a locality (https://whosonfirst.mapzen.com/spelunker/id/101750367/).  London’s hierarchy lists City of Westminster as it’s region.  However, London’s polygon is much larger area-wise than City of Westminster’s polygon.  Is it correct that in this case a locality can entirely contain a region?

**Comment by nvkelso** [comment] 2016-03-14 18:07
While Who's On First does aim to support "unitary" city-county-region combined administrative structures, London vis-a-vis Westminster is a data bug we inherited from Quattroshapes. Something more on the order of "London, Greater London" would be more appropriate.

**Comment by trescube** [comment] 2016-03-15 20:04
Our first result in Pelias is for "London, Greater London", which comes from geonames, so what you're saying makes sense.  We noticed this while gearing up for the switch to WOF since it's in our acceptance tests.  Is this a one-off data bug or part of a bigger problem from QS?

**Comment by nvkelso** [comment] 2016-03-15 20:14
Stuff in UK is always a little weird, so there are likely a few more issues like this. Suggest spot checking other large cities in the country. Elsewhere in Europe Quattroshapes mostly had better data to work with.

**Comment by trescube** [comment] 2016-03-15 20:35
I'll poke around in the data.  Is this something we can/should submit PRs for or are issues sufficient?

**Comment by nvkelso** [comment] 2016-03-15 20:41
Either PRs or issues are good :)

**Comment by missinglink** [comment] 2017-11-22 14:14
heya, surfaced this issue again today, https://whosonfirst.mapzen.com/spelunker/id/404435563/ still has a blank name and appears to be a geometric duplicate of https://whosonfirst.mapzen.com/spelunker/id/85684061/

I know it's a long-standing issue, is it possible that an easy fix is to merge these two records?

**Comment by stepps00** [comment] 2017-11-22 15:36
We are actively working on #411, which affects both of the linked records above. The admin records for the core of London should be done soon.

Next week, I will chat with @zbsingleton to figure out if a quick interim fix for these two records is possible.

**Comment by stepps00** [comment] 2017-12-20 22:45
Noting that this will be taken care of shortly through the work done in #411.

The City of Westminster is a "borough, with city status".

**Comment by stepps00** [comment] 2017-12-22 19:48
This issue has been fixed, new and updated records for London were recently imported. Closing issue.

**Closed by stepps00** 2017-12-22 19:48 UTC
