### ISSUE TITLE
Duplicate New Delhi

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1785] opened 2020-01-14 15:23 UTC
Looks like there are two record for the district of [New Delhi](https://en.wikipedia.org/wiki/New_Delhi):

- [890511421](https://spelunker.whosonfirst.org/id/890511421/): has concordances, alt-names, geometry
- [890509685](https://spelunker.whosonfirst.org/id/890509685/): no geometry, not quite as many concordances
![Screenshot_2020-01-14_07-21-56](https://user-images.githubusercontent.com/111716/72356842-ce2cda00-369e-11ea-909a-53b5e30ee51a.png)

**Comment by stepps00** [comment] 2020-01-15 07:08
https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/master/data/890/509/685/890509685.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/master/data/890/511/421/890511421.geojson

Like #1784, these changes aren't appearing in the Spelunker yet.. but this issue should be fixed.

These records are different placetypes, one at the county placetype representing the "district", one at the locality placetype representing the "city". The locality was a duplicate of another record, so it was flagged as not current, while the county record was kept current.

**Closed by stepps00** 2020-01-15 07:08 UTC

**Comment by orangejulius** [comment] 2020-01-15 20:04
Oh, so sorry for the noise on both of these! I totally forgot to check the actual raw files.

**Comment by stepps00** [comment] 2020-01-16 06:57
No worries - I opened https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/145 to untangle why Github and the Spelunker are seemingly out of sync.
