### ISSUE TITLE
Missing France and Switzerland county names

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#152] opened 2015-11-10 00:35 UTC
The following Switzerland and France counties are missing names:

102062797
102062895
102062917
102063021
102071301
102071599
102071635
102071683
102071689
102071875

**Comment by stepps00** [comment] 2016-05-17 23:04
Extended list of Swiss counties missing `wof:name` fields:

102062797
102062879
102062823
102063003
102062787
102063021
102063007
102062917
102062973
102062921
102063067
102062951
102063043
102063053
102062935
102062937
102063057
102062895
102062901
102063011

These county records have the same geometry and dependents as the region in their hierarchy. For instance, in the record for [`102062797`](https://whosonfirst.mapzen.com/spelunker/id/102062797/#9/47.0317/8.1752), the region record for [Lucerne](https://whosonfirst.mapzen.com/spelunker/id/85682319/#9/47.0317/8.1752) listed in the hierarchy. Lucerne has the same geometry and dependent records, so the likely solution for this list is to add a `wof:name` equal to the record's region hierarchy record.

**Comment by stepps00** [comment] 2016-05-17 23:29
Extended list of the county records in France that are missing a `wof:name` - solution will be different than the solution for Swiss name changes because the geometries do not match any records in the hierarchy.

[france_noname.txt](https://github.com/whosonfirst/whosonfirst-data/files/269357/france_noname.txt)

**Comment by stepps00** [comment] 2016-06-06 21:58
[Most recent commit](9dca283) took care of this issue for records in Switzerland. The records in France will be taken care of in an upcoming commit.

**Comment by stepps00** [comment] 2017-06-15 17:58
This is actually a forward dupe of #53. All records with a blank or "null" wof:name property will be tracked in #53.

Closing issue and disregarding the commit linked above.

**Closed by stepps00** 2017-06-15 17:58 UTC
