### ISSUE TITLE
404435563 is a localadmin in London with a blank name

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#825] opened 2017-06-16 02:45 UTC
https://whosonfirst.mapzen.com/spelunker/id/404435563/ is a bit odd. It's a localadmin with a blank name somewhere in London. It has the City of Westminster (a region) as its parent.

Interestingly, the locality of London is a direct child of this mysterious localadmin: https://whosonfirst.mapzen.com/spelunker/id/101750367/

So we have a hierarchy that looks like this:

- Europe (continent) https://whosonfirst.mapzen.com/spelunker/id/102191581/
  - United Kingdom (country) https://whosonfirst.mapzen.com/spelunker/d/85633159/
    - England (macroregion) https://whosonfirst.mapzen.com/spelunker/d/404227469/
      - City of Westminster (region) https://whosonfirst.mapzen.com/spelunker/d/85684061/
        - <blank - 404435563> (localadmin) https://whosonfirst.mapzen.com/pelunker/id/404435563/
          - London (locality) https://whosonfirst.mapzen.com/spelunker/id/101750367/

This seems strange to me. Is having City of Westminster be a parent of London the right thing? What's going on with 404435563 not having a name?

**Comment by stepps00** [comment] 2017-06-16 16:34
Hey @simonw - thanks for filing the issue.

You're right, this _is_ strange. This is actually a known error in Who's On First and we have an active issue tracking updates to a group of records that currently have a blank of `null` `wof:name` property. 

We have https://github.com/whosonfirst-data/whosonfirst-data/issues/53 open to track this work, which I plan on opening a PR for shortly. Because I want to track all work in a single Git issue, I'm going to close this in favor of #53.

To answer you questions, though...

> Is having City of Westminster be a parent of London the right thing?

The [City of Westminster](https://en.wikipedia.org/wiki/City_of_Westminster) does have the correct geometry, but is incorrectly listed as the sole parent record to London. Like [New York City](https://whosonfirst.mapzen.com/spelunker/id/85977539/#9/40.6979/-73.9797), we would probably need to build a dual hierarchy that includes several `localadmin` records. 

> What's going on with 404435563 not having a name?

During import, ~300 `localadmin` records were in GB were given no `wof:name`, this record being one of them.

Thanks again and feel free to track that issue for updates!

**Comment by stepps00** [comment] 2017-06-16 16:34
Fwd dupe of https://github.com/whosonfirst-data/whosonfirst-data/issues/53.

**Closed by stepps00** 2017-06-16 16:34 UTC

**Comment by nvkelso** [comment] 2017-06-16 16:59
Re:

> The City of Westminster does have the correct geometry, but is incorrectly listed as the sole parent record to London. Like New York City, we would probably need to build a dual hierarchy that includes several localadmin records.

Re-opening this issue to track the **hierarchy** fixes described above.

**Comment by stepps00** [comment] 2017-06-16 18:30
We also have https://github.com/whosonfirst-data/whosonfirst-data/issues/225 open.. I'd prefer to track in one of the previous issues, if possible.

**Comment by nvkelso** [comment] 2017-06-16 20:26
Agree this is a dup of #225, thanks for linking up :)
