### ISSUE TITLE
Mystery Bangalore IN

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2190] opened 2024-04-19 10:53 UTC
The record [locality:1310469483](https://spelunker.whosonfirst.org/id/1310469483/) is labelled as Bangalore in [Tamil Nadu](https://spelunker.whosonfirst.org/id/85672245/).

It's easily confused with [locality:102030819](https://spelunker.whosonfirst.org/id/102030819/) which is the well known capital city of Karnataka.

The geometry is also suspicious, as the scale seems to indicate it is a small area, maybe a venue or campus? 🤔 

<img width="451" alt="Screenshot 2024-04-19 at 12 52 17" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/738069/ac086482-a088-4ea2-ab05-3efa9a43091c">

Can we please either delete this or reclassify it?

**Comment by nvkelso** [comment] 2024-04-19 16:29
Who's On First observes the Bangalore in Tamil Nadu both via Karmashapes and via Geonames, so the feature shouldn't be deleted.

Given that these two seemingly legitimate features are in different states (which helps with disambiguation), then I wonder why this tiny place is sorting before the mega city. 

It appears `wof:population` value for the tiny place is sourced from `ks:ks_pop` = `367` (no change suggested) and the mega city is in error somehow sourced from `ks:ks_pop` = `187` when it should probably be sourced from `gn:population` = `5104047` instead. Correcting the `wof:population` and the `src:population` for the megacity would fix the sorting issue.

Root cause expansion: Let's see how many other megacities in India may have incorrectly had their populations downsized during the Karmashapes import.

**Comment by nvkelso** [comment] 2024-04-19 16:36
I tried to make this change via Write Field but filing the Github PR via the API times out. Tried again via Github.com and it errors `There was an error committing your changes: File could not be edited` after around 8 seconds and error repeats on retry. Can someone else try or I'll try again Monday.

**Comment by missinglink** [comment] 2024-04-22 10:28
Out of curiosity, when a record has a KS ID such as this one `KS5D08C5FE94E54D01A2DDEFB7DFC8055C`, what is the method to find the original source of the data? I'd like to look this one up specifically and see what metadata it has.

**Comment by justinelliotmeyers** [comment] 2024-04-22 12:16
Ministry of Rural Development, 2022. PMGSY Rural Connectivity Datasets, https://geosadak-pmgsy.nic.in/opendata/. Published under India’s Government Open Data License: [https://data.gov.in/government-open-data-license-india ](https://data.gov.in/government-open-data-license-india)

India Village-Level Geospatial Socio-Economic Data Set, v1 (1991, 2001) – [India Village-Level Geospatial Socio-Economic Data Set, v1: India Data Collection | SEDAC (columbia.edu)](https://sedac.ciesin.columbia.edu/data/set/india-india-village-level-geospatial-socio-econ-1991-2001)

Geographic Names Server (GNS) – https://geonames.nga.mil/geonames/GNSData/

**Comment by justinelliotmeyers** [comment] 2024-04-22 12:17
@missinglink If you have concerns with the actual location, please let me know. I can do more investigation if needed, but haven't looked at india data in months.

**Comment by missinglink** [comment] 2024-04-22 16:12
It seems correct, well at least it's a verbatim representation of the source govt data, I had a look and the original data doesn't have any more clues about what it is, presumably just a confusingly similar name for a small town.

Once the population fix for the megacity lands it should at least sort lower in search results.

**Comment by nvkelso** [comment] 2024-04-22 20:15
Fixed via https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/140 to correct the population for the megacity.

It's normal (if not annoying) for same-named towns like this so no further action suggested.

**Closed as completed by nvkelso** 2024-04-22 20:15 UTC
