### ISSUE TITLE
New data parse issue

### ISSUE THREAD

**Issue by roja** [whosonfirst-data/whosonfirst-data#818] opened 2017-06-07 07:10 UTC
Following error when running the import for wof data:

2017-06-07T00:59:54.261Z - ^[[31merror^[[39m: [whosonfirst] exception parsing JSON in file 110/870/262/3/1108702623.geojson: TypeError: Path must be a string. Received undefined

Strange thing this time is that the file doesn't appear in this repository...

**Comment by thisisaaronland** [comment] 2017-06-07 14:36
Huh, that's weird. `1108702623` is a venue: 

https://whosonfirst.mapzen.com/spelunker/id/1108702623

My first thought was that one of the meta files got messed up but it doesn't look that way on our end:

```
$> cd /usr/local/data/whosonfirst-data
$> ll data/110/870/262/3/1108702623.geojson
ls: cannot access data/110/870/262/3/1108702623.geojson: No such file or directory
$> grep 1108702623 meta/*.csv | wc -l
0
```

What tool or script are you running to trigger the error?

**Comment by roja** [comment] 2017-06-07 15:55
git clone https://github.com/pelias/whosonfirst.git
cd whosonfirst
npm run download
npm start

approximately...

**Comment by roja** [comment] 2017-06-07 15:56
issue also raised in the importer repo: pelias/whosonfirst#237

**Comment by trescube** [comment] 2017-06-07 18:31
There doesn't seem to be anything wrong with the bundle files, it's most likely an error caused by the pelias whosonfirst importer.  @thisisaaronland you can close this.

**Closed** 2017-06-07 18:35 UTC
