### ISSUE TITLE
records parented by multiple continents

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#715] opened 2017-04-04 19:01 UTC
some records appear to belong to two continents at the same time.

is this correct? is it valid for a place belong to multiple continents?

eg: https://whosonfirst.mapzen.com/spelunker/id/404429075

here's a list of 38 records which belong to both `Europe` and `North America`:

```
[ 85671191,
  404429029,
  404429033,
  404429035,
  404429037,
  404429039,
  404429041,
  404429043,
  404429045,
  404429047,
  404429051,
  404429053,
  404429055,
  404429057,
  404429059,
  404429061,
  404429063,
  404429065,
  404429069,
  404429071,
  404429073,
  404429075,
  404429077,
  404429079,
  404429081,
  404429083,
  404429087,
  404429089,
  404429091,
  404429093,
  404429095,
  404429097,
  404429099,
  404429101,
  404429105,
  890444821,
  890444823,
  890444825 ]
```

**Comment by stepps00** [comment] 2017-04-04 19:30
After spot-checking these records, it looks like this is affecting [the region of Martinique]() and any child records. This is caused by Martinique being parented by both the country of Martinique (North America) and the country France (Europe), which is incorrect. 

I am going to keep this issue and propose a follow up PR - if you come across any additional records, feel free to paste the `wof:id`s in a new comment.. thanks @missinglink !

**Comment by stepps00** [comment] 2017-04-06 20:58
**Note**: This same issue is occurring with features in French Guyana. For instance, [Cayenne](https://whosonfirst.mapzen.com/spelunker/id/404429109/#9/5.3221/-53.0928) is parented by both South America and Europe. 

This issue should be used to track updates to all features with dual-hierarchies that have two continents. To find these features, download all country features, display them in QGIS, and review all records where country geometries overlap.

**Comment by missinglink** [comment] 2017-04-12 11:11
This is possibly related? The `country` of France has a very large bbox because the geometry includes islands from the `empire` of France.

https://whosonfirst.mapzen.com/spelunker/id/85633147

**Comment by missinglink** [comment] 2017-04-12 11:27
here's the full list of records with dual continent parentage:

```
Asia / North America
[ 85632711 ]
South America / North America
[ 85632563, 85681155 ]
Europe / Seven Seas
[ 85671199,
  404428903,
  404428907,
  404428909,
  404428911,
  404428913,
  404428915,
  404428917,
  404428919,
  404428921,
  404428925,
  404428927,
  404428929,
  404428931,
  404428933,
  404428935,
  404428937,
  404428939,
  404428943,
  404428945,
  404428947,
  404428949,
  404428951,
  404428953,
  404428955,
  890415453,
  890415455,
  890430411,
  890450115,
  890450117,
  890450119 ]
Europe / North America
[ 85671191,
  404429029,
  404429033,
  404429035,
  404429037,
  404429039,
  404429041,
  404429043,
  404429045,
  404429047,
  404429051,
  404429053,
  404429055,
  404429057,
  404429059,
  404429061,
  404429063,
  404429065,
  404429069,
  404429071,
  404429073,
  404429075,
  404429077,
  404429079,
  404429081,
  404429083,
  404429087,
  404429089,
  404429091,
  404429093,
  404429095,
  404429097,
  404429099,
  404429101,
  404429105,
  890444821,
  890444823,
  890444825 ]
Europe / Asia
[ 85632601,
  101749141,
  101756147,
  101756157,
  101756159,
  101756161,
  101756163,
  101803377,
  101803379,
  101803381,
  101803385,
  101803485,
  101803487,
  101803489,
  101803493,
  101803495,
  101803497,
  101803499,
  101803501,
  101803503,
  101803505,
  101803507,
  101803511,
  101803513,
  101803515,
  101803517,
  101803519,
  101803521,
  101803523,
  101803525,
  101803529,
  101803531,
  101803593,
  101803595,
  101803597,
  101838575,
  101838577,
  101838579,
  101838581,
  101838583,
  101838585,
  101838587,
  101838589,
  101838593,
  101838595,
  101838597,
  101850051,
  101850103,
  101850131,
  101850133,
  101850135,
  101850137,
  101850143,
  101857773,
  101875097,
  101875099,
  101875101,
  101875141,
  101875143,
  101875145,
  101875147,
  101875151,
  101911713,
  102011315,
  890452063 ]
Europe / South America
[ 85632195,
  85671195,
  404429107,
  404429109,
  404429111,
  404429113,
  404429115,
  404429117,
  404429119,
  404429123,
  404429125,
  404429127,
  404429129,
  404429131,
  404429133,
  404429135,
  404429137,
  404429141,
  404429143,
  404429145,
  404429147,
  404429149,
  404429151,
  404429153,
  890429521,
  890442055,
  890444589,
  890444593,
  890444595,
  1091680601,
  1091680627,
  1091680649,
  1091680671,
  1091680691,
  1091680721,
  1091680751,
  1091680763,
  1091680781,
  1091680813,
  1091680851,
  1091680871,
  1091680885,
  1091680907,
  1091680925,
  1091680943,
  1091680969,
  1091680995,
  1091681021,
  1091681039,
  1091681061,
  1091681087 ]
Africa / Asia
[ 85632349 ]
Africa / Europe
[ 85671203,
  404428865,
  404428867,
  404428871,
  404428873,
  404428875,
  404428877,
  404428879,
  404428881,
  404428883,
  404428885,
  404428889,
  404428891,
  404428893,
  404428895,
  404428897,
  404428899,
  404428901,
  890435415,
  890435417,
  890435419,
  890436597,
  890436875,
  890436953,
  890436955 ]
```

**Comment by nvkelso** [comment] 2017-04-12 14:52
The label bbox should be tight on Metropolitan France, but the geom bbox should include its overseas regions.

**Comment by stepps00** [comment] 2017-04-12 17:02
Thanks for the list.. I have a feeling the majority of these features are both part of an overseas dependency _and_ part of a top-level country. I'll poke around and propose a PR to fix.

**Comment by stepps00** [comment] 2017-06-19 21:41
Much of this will be taken care of via https://github.com/whosonfirst-data/whosonfirst-data/issues/2.

**Comment by stepps00** [comment] 2017-08-04 18:04
#2 landed and took care of the multiple continent parenting issue in French overseas territories.

I will take a look at the other records in the lists above, but at first glance, the other records have a `disputed` placetype (meaning a multiple hierarchy is expected).

Likely closing this issue and opening follow up issue(s) for one-offs.

**Comment by stepps00** [comment] 2017-08-04 18:06
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/580

Closing issue.

**Closed by stepps00** 2017-08-04 18:06 UTC
Labels: admin-0 country, admin-1 region, LOE:Medium, properties, reversegeo
