### ISSUE TITLE
Localities Missing Name

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1864] opened 2020-07-07 22:36 UTC
Below is a list of locality IDs that are missing a wof:name. The second column is the name:eng_x_preferred or NULL if that is not available, so most I think could be fixed by using the data already available. Or perhaps qs: loc_alt would be better.

101788901	Grainau
101785433	Finsing
101784211	Gablingen
101827081	Eggolsheim
101841353	Friedersdorf
101817375	NULL
101842051	Neuhausen ob Eck
101812211	Glauburg
102012969	NULL
101786667	Baierbrunn
101841295	Langendorf
101759701	Helmstadt-Bargen
101842109	Grafenau
101759709	Zuzenhausen
102014933	NULL
101842629	Malterdingen
101809963	Guxhagen
101847831	Kötz
101842625	Gutach im Breisgau
101819563	Denkte
101819733	NULL
101846229	Osann-Monzel
101810829	Kalbach
101842627	Gutach im Breisgau
101842223	NULL
101765113	NULL
101855593	Glan-Münchweiler
101764261	Erolzheim
101807789	NULL
101784335	Niederaichbach
101842643	NULL
101796033	Nikopol
101855443	Babensham
102011881	Yekaterinburg
101782137	Wilburgstetten
101846311	NULL
101841211	NULL
101874431	Friedrichskoog
101847241	NULL
102011129	Saratov
102010001	Saransk
102011627	Samara
102010453	Tol'yatti
102013341	Barnaul
102006831	Volzhskiy
102006815	Volzhsky
102010361	Buguruslan
102012707	Anzhero-Sudzhensk
102012673	Tomsk
102004815	Gryazi
102015409	Komsomolsk-on-Amur
102015413	Komsomolsk-on-Amur
102011833	Asbest
102014353	Kyzyl
102015119	Blagoveshchensk
102015089	Belogorsk
101842115	Grafenau
101785385	Hilgertshausen-Tandern
101782193	NULL
101812053	Wildflecken
101855513	Bad Peterstal-Griesbach
101842107	NULL
101928943	NULL
102001747	NULL
102005185	Uvarovo
102001899	Monchegorsk
102001893	Olenegorsk
102001553	Sovetskaya Gavan
102001561	Sovetskaya Gavan'
102001543	Sovetskaya Gavan
102015227	Izvestkovyy
101820711	Luisenthal
101818631	NULL
101818673	Dobin am See
102011299	Krasny Kut
102013257	Osinniki
102015103	Srednebelaya
102010003	NULL
102001889	Murmashi
102015427	Khurba
102015077	Novy Urgal
102009081	Vasilyevo
102014917	Priargunsk
102012199	Ikovka
102004459	Golovinskaya Varezhka
102014291	Mal'ta
102001821	NULL
101806375	Handeloh
101822169	NULL
101853435	Hohenfels
101847197	NULL
101820849	Schönewalde
101874425	NULL

**Comment by stepps00** [comment] 2020-07-08 05:25
Thanks @henrylyne - I'll take a look and update the `wof:name` values. Was this list created against all per-country repos or a subset of the whosonfirst-data repos?

**Comment by henrylyne** [comment] 2020-07-08 17:00
@stepps00 it was generated against all countries. I could include more data if that would be helpful, just let me know what else you would like

**Comment by stepps00** [comment] 2020-10-01 20:09
Hey @henrylyne - I'm going to close this issue as a duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/1425.. that issue will take care of all of the records you've listed above.

**Closed by stepps00** 2020-10-01 20:09 UTC
