### ISSUE TITLE
Add Pertisau locality in Austria

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#562] opened 2016-12-15 23:58 UTC
A user contacted us through support to report that the city is not being returned in the search result for this address in Austria. 

http://search.mapzen.com/v1/search/structured?address=Pertisau%2017d&country=Austria

Here are the relevant admin hierarchy results from this query. There is no locality listed, and the user reports that it should be "Pertisau", too. 

"properties": {
"country": "Austria",
"country_gid": "whosonfirst:country:85632785",
"country_a": "AUT",
"region": "Tirol",
"region_gid": "whosonfirst:region:85681661",
"county": "Schwaz",
"county_gid": "whosonfirst:county:102049755",
"label": "17b Pertisau, Austria"
}

Looking in Who's on First, I'm seeing only venues matching Pertisau and no localities. Geonames does have it, though.

https://whosonfirst.mapzen.com/spelunker/search/?q=pertisau#14/47.4311/11.6961

See also https://github.com/whosonfirst-data/whosonfirst-data/issues/546 for general discussion on locality polygons in Austria.

**Comment by nvkelso** [comment] 2016-12-16 22:02
This is better tracked as a duplicate of #107 to add the remaining Quattroshapes gazetteer point features to Who's On First (which includes this **Pertisau** `locality`), where #546 tracks adding `localadmin` (in this case **Eben am Achensee** which is Pertisau's parent.)

<img width="774" alt="screen shot 2016-12-16 at 13 59 05" src="https://cloud.githubusercontent.com/assets/853051/21280003/46ccecf2-c398-11e6-8374-2178b19c5862.png">

**Comment by nvkelso** [comment] 2016-12-16 22:04
Confirmed the original search result was an `address`, missing any hierarchy but region and country.

<img width="562" alt="screen shot 2016-12-16 at 14 03 45" src="https://cloud.githubusercontent.com/assets/853051/21280041/7e4adb3a-c398-11e6-93d3-07212b625223.png">

**Closed** 2016-12-16 22:04 UTC
