### ISSUE TITLE
Shapes are invalid when importing them into Elasticsearch

### ISSUE THREAD

**Issue by peterneubauer** [whosonfirst-data/whosonfirst-data#975] opened 2017-10-09 08:07 UTC
Hi,
we are using the WOF shapes for Mapillary top lists. Works great, however, some shapes are not valid geodata according to the Elasticsearch parser when trying to index them in our ELS 2.4. Examples:
```
# invalid holes in shapes countries
remove_holes_shapes = [
    '85632475',
    '85632505',
    '85632469',
    '85632761',
    '85632793',
    '85632449',
    '85632773',
    '85632475',
    '85632505',
    '85632469',
    '85632761',
    '85632793',
    '85632449',
    '85632773',
]
```

Duplicate oordinate in countries:

```
duplicate_coords = {
    '85632693': {
        'error': 'invalid_shape_exception: Provided shape has duplicate consecutive coordinates at: (-12.055823, 25.99583, NaN)'}
}


```
Is there any chance we can submit you feedback for the shapes and work on making them valid?

**Comment by stepps00** [comment] 2017-10-09 15:18
Hi @peterneubauer - thanks for filing the issue. A list of affected `wof:id` values is great and any additional information you have about the specific records is helpful, too. 

We've seen this issue pop up before.. I suspect this issue touches more than the list of records you created above. I will look into this issue and propose a fix through a PR.

**Comment by stepps00** [comment] 2017-10-10 17:57
@peterneubauer - are you able to provide the error that you receive when indexing these records in ELS 2.4? I'd like to update these records' self-intersecting interior rings so they can be handled in Elasticsearch.

**Comment by peterneubauer** [comment] 2017-10-16 12:08
Let me update the repo, and reimport everything to see if I still get errors - will report back!

**Comment by peterneubauer** [comment] 2017-10-31 13:30
So, I'm constructing a test that tries to import all shapes that are relevant to use and logs errors withohut fixing them. One simple start is Antarctica (will try to make a full list):

```
root@72bf36176b00:/mapillary_source# nose2 -s tests/integration/mapillary_geoshapes/ test_faulty_wofs
0: index 85682211 - b'D E   M A G A L L A N E S   y   A N T A R T I C A   C H I L E N A'
WARNING:elasticsearch:PUT http://elasticsearch_provider:9200/wofs/wof/85682211/_create [status:400 request:11.433s]
RequestError(400, 'mapper_parsing_exception', {'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'failed to parse [shape]'}], 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'Points of LinearRing do not form a closed linestring'}, 'type': 'mapper_parsing_exception', 'reason': 'failed to parse [shape]'}, 'status': 400})

```

**Comment by nvkelso** [comment] 2017-10-31 17:07
> [{'type': 'mapper_parsing_exception', 'reason': 'failed to parse
[shape]'}], 'caused_by': {'type': 'illegal_argument_exception', 'reason':
'Points of LinearRing do not form a closed linestring’}

Do we know what mapping lib is used in ElasticSearch to determine the
error? Hopefully it’s GEOS...

**Comment by thisisaaronland** [comment] 2017-10-31 17:17
I am pretty sure that at the end of the day it's the Java Topology Suite. ES uses:

https://github.com/locationtech/spatial4j 

Which in turn uses:

https://sourceforge.net/projects/jts-topo-suite/

Unfortunately I am not sufficiently familiar with Java to just whip up a simple-dumb "validate this thing" tool which would be a nice thing to have, in general...

**Comment by nvkelso** [comment] 2017-10-31 17:27
It all comes down to JTS in the end, so that's good at least to have one point of feature improvement. We'll see if anyone contacts me after my Twitter missive ;)

**Comment by thisisaaronland** [comment] 2017-10-31 17:33
If web browsers can render broken markup...

**Comment by peterneubauer** [comment] 2017-11-01 08:49
There is https://gis.stackexchange.com/questions/90041/converting-parsing-geojson-into-com-vividsolutions-jts-geometry so it seems it wouldn't be too hard to write java for this. I would suggest doing it in this project, want me to write it?

**Comment by thisisaaronland** [comment] 2017-11-01 18:13
@peterneubauer – This is great, thanks!

If we created a proper `java-whosonfirst-jts` repo and made you a contributor would you be willing to move your code over there?

This would be a super useful tool and as time and circumstances permit I'd like to make it a proper library that can be invoked from the command line and/or things like a dropwizard tool. 

(I know enough Java that I can probably start poking at your work; it's the getting started part that still leaves me stumbling around in the dark :-)

Longer term it would be nice to replicate the input/indexing functionality of the `go-whosonfirst-index` package [1] but for now just being able to validate individual records and/or meta files would be super useful.

[1] https://github.com/whosonfirst/go-whosonfirst-index/blob/master/index.go#L110-L215

**Comment by peterneubauer** [comment] 2017-11-01 20:03
yes, no problem. Just make me a contributor, and I can move over the code. I'm using a static extraction b place_type to pull the files so we don't have to clone this repo as part of the test, will see if I can port that, too, it's in python right now.

**Comment by peterneubauer** [comment] 2017-11-02 09:01
Code imported into https://github.com/whosonfirst/java-whosonfirst-jts, will now report errors in the output, feel free to reformat. Works?

**Comment by nvkelso** [comment] 2017-11-02 15:31
@peterneubauer will it also fix the errors or will a separate tool be needed for that?

**Comment by thisisaaronland** [comment] 2017-11-02 16:12
@nvkelso it does not fix anything, it's simply the work to sanity check and report bunk geometry now wearing a warm and comfy WOF sweater.

**Comment by peterneubauer** [comment] 2017-11-02 17:56
Yes, right now we are fixing geometries with PSQL ST_Simplify and Shapely (python) and actual removal of offending holes and duplicate coordinates, but it's of course MUCH better to test and find these offending geometries and fix them at the source - here :)

Just added the generating script in https://github.com/whosonfirst/java-whosonfirst-jts/blob/master/src/main/python/generate_wof_url_lists.py (I'm not a python export, so forgive the ugly code) so you can generate the lists yourself.

**Comment by stepps00** [comment] 2017-11-02 21:53
@peterneubauer - thanks for the update! If possible, we'd like to hear how you're dealing with/fixing these invalid geometries on your end. If you have sample code or a repo, feel free to link :)

**Comment by peterneubauer** [comment] 2017-11-03 10:47
Added some more code to demo simplification using shapely in SimplifyUtils.py (and PostGIS, but not used right now)

**Comment by peterneubauer** [comment] 2017-11-04 17:22
There is a good blog post on postgis and performance here https://carto.com/blog/inside/postgis-performance/, in the simplify utility python class you can see that, if you have postgis installed and put in the environment variables, you can use their engine to validate and simplify things. This IA however nit working in all cases but might be a good replacement for our manual removal if duplicate coordinates for instance.

**Comment by peterneubauer** [comment] 2017-11-06 14:21
@stepps00 let me know how we can proceed here, would be great to get the shapes into shape :)

**Comment by stepps00** [comment] 2017-11-06 17:22
Hey @peterneubauer - thanks for the updates. Let me poke around today, I'll respond in this issue with ideas to proceed.

**Comment by peterneubauer** [comment] 2017-11-13 12:28
Good, let me know if you need help getting started, I would like us to make progress towards valid shapes rather sooner than later.

**Comment by peterneubauer** [comment] 2017-11-22 13:26
I updated the first comment with the manual fixes on country level that we are doing now.

**Comment by nvkelso** [comment] 2018-08-23 22:16
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1071

**Comment by thisisaaronland** [comment] 2018-08-29 00:08
Have you checked the ordering of the rings? The issue is not so much Elasticsearch as it is JTS, which ES uses under the hood.

**Comment by stepps00** [comment] 2018-08-29 00:34
I haven't checked this in the recent validation work, but I'm guessing the right-hand rule for outer/inner rings is causing Elasticsearch to throw these errors. 

The GeoJSON spec says that GeoJSON should follow this rule, but also suggests:

```
For backwards compatibility, parsers SHOULD NOT reject polygons that do not follow the right-hand rule.
```

I think the next step would be to do a second pass at correcting geometries that don't follow the right-hand rule.

https://tools.ietf.org/html/rfc7946

**Comment by thisisaaronland** [comment] 2018-08-29 16:41
JTS predates GeoJSON by a while and anyway the former doesn't know about the latter, per se, only an internal representation of a geometry.

**Comment by stepps00** [comment] 2021-03-30 00:25
Bumping this issue because I've found a solution using Shapely that should fix these long-standing geometry issues. Some of the records listed in this issue have already had their geometries fixed, but [here](https://github.com/whosonfirst-data/whosonfirst-data/files/6225294/invalid_ids.csv.txt) is a list of records that seem to still be invalid.

I'll try to prioritize this issue this week, link PRs, then close this issue.

**Comment by stepps00** [comment] 2021-04-15 21:47
Some additional validation work done on WOF's `constituency` geometries, added [here](https://github.com/whosonfirst-data/whosonfirst-data-constituency-us/commit/57626b41a23a74d6fda7b303d976effe6e7aa972?short_path=c0c5c5d#diff-c0c5c5d511e584d5c41e0ebc3d2e9c4bbff2a57b60bef3db36345421e7829404).

**Comment by stepps00** [comment] 2022-01-19 00:41
This issue should be fixed. All WOF geometries are valid according to the GeoJSON spec, and should index in ElasticSearch without issue.

**Closed by stepps00** 2022-01-19 00:41 UTC
Labels: geometry
